### ISSUE TITLE
NIP-51

### ISSUE THREAD

**Issue by verbiricha** [sepehr-safari/listr#1]
Hey, thanks for writing listr, looks really promising. What do you think about using the [NIP-51](https://github.com/nostr-protocol/nips/blob/master/51.md) standard kinds 30000 for lists of people and 30001 for bookmark lists? I noticed you are using kind 37777 for some reason.

**Comment by sepehr-safari** [comment]
Thanks man.
the real issue is that those kinds of events are mostly used by other famous clients (eg. damus) and it might be confusing or causing some unexpected behaviours and finally may result in loss of user's data.
so, we decided to use a unique kind for Listr.
ps: now it's 33777.
